### ISSUE TITLE
build_discriminator

### ISSUE THREAD

**Issue by AvivSham** [srihari-humbarwadi/cartoon_gan_tf2.0#1]
https://github.com/srihari-humbarwadi/cartoon_gan_tf2.0/blob/5418312fb294bc73d07a2a5fd301324d6d4de940/cartoon_gan.py#L101

I didn't open pull request since its a really minor change. I think you have a bug in build_discriminator function, you iterate over i but inside the loop the number of filters equals to f[0] and I think you meant to f[i].
Hope that helps :)

**Comment by srihari-humbarwadi** [comment]
Thank you for the fix, merged https://github.com/srihari-humbarwadi/cartoon_gan_tf2.0/pull/2
